# qpb::core and qpb::widgets as one static library, built from the component
# folder with the settings of qpb/CMakeLists.txt (qpb/cmake/qpbTargetHelpers.cmake).

include(../qpb.pri)

TEMPLATE = lib
CONFIG += staticlib
TARGET = qpb
QT = core widgets

# Globbed, so files added to qpb/ need no change here.
HEADERS += \
    $$files($$QPB_ROOT/include/qpb/*.h) \
    $$files($$QPB_ROOT/include/qpb/widgets/*.h) \
    $$files($$QPB_ROOT/src/core/*.h) \
    $$files($$QPB_ROOT/src/widgets/*.h)
SOURCES += \
    $$files($$QPB_ROOT/src/core/*.cpp) \
    $$files($$QPB_ROOT/src/widgets/*.cpp)
INCLUDEPATH += $$QPB_ROOT/src

DEFINES += \
    QT_NO_CAST_FROM_ASCII \
    QT_NO_CAST_TO_ASCII \
    QT_NO_URL_CAST_FROM_STRING \
    QT_DISABLE_DEPRECATED_UP_TO=0x060500

# include/qpb/qpbversion.h from qpb/VERSION, as configure_file() does in CMake.
# Written only when it changes, so running qmake again rebuilds nothing.
QPB_VERSION_STRING = $$cat($$QPB_ROOT/VERSION, lines)
QPB_VERSION_STRING = $$first(QPB_VERSION_STRING)
!contains(QPB_VERSION_STRING, "^[0-9]+[.][0-9]+[.][0-9]+(-[0-9A-Za-z.]+)?$"): \
    error("qpb: invalid VERSION \"$$QPB_VERSION_STRING\"")
QPB_VERSION_NUMBER = $$section(QPB_VERSION_STRING, -, 0, 0)
QPB_VERSION_MAJOR = $$section(QPB_VERSION_NUMBER, ., 0, 0)
QPB_VERSION_MINOR = $$section(QPB_VERSION_NUMBER, ., 1, 1)
QPB_VERSION_PATCH = $$section(QPB_VERSION_NUMBER, ., 2, 2)

QPB_VERSION_H = $$cat($$QPB_ROOT/cmake/qpbversion.h.in, blob)
# Line ends: write_file() writes the platform's own, so drop any CR here.
QPB_VERSION_H = $$replace(QPB_VERSION_H, "\\r", "")
QPB_VERSION_H = $$replace(QPB_VERSION_H, "\\s+\\z", "")
QPB_VERSION_H = $$replace(QPB_VERSION_H, "Generated by CMake", "Generated by qmake")
QPB_VERSION_H = $$replace(QPB_VERSION_H, "@QPB_VERSION_MAJOR@", $$QPB_VERSION_MAJOR)
QPB_VERSION_H = $$replace(QPB_VERSION_H, "@QPB_VERSION_MINOR@", $$QPB_VERSION_MINOR)
QPB_VERSION_H = $$replace(QPB_VERSION_H, "@QPB_VERSION_PATCH@", $$QPB_VERSION_PATCH)
QPB_VERSION_H = $$replace(QPB_VERSION_H, "@QPB_VERSION_STRING@", $$QPB_VERSION_STRING)

QPB_VERSION_FILE = $$QPB_BUILD_DIR/include/qpb/qpbversion.h
exists($$QPB_VERSION_FILE) {
    QPB_VERSION_OLD = $$cat($$QPB_VERSION_FILE, blob)
    QPB_VERSION_OLD = $$replace(QPB_VERSION_OLD, "\\r", "")
    QPB_VERSION_OLD = $$replace(QPB_VERSION_OLD, "\\s+\\z", "")
}
!equals(QPB_VERSION_OLD, $$QPB_VERSION_H) {
    mkpath($$dirname(QPB_VERSION_FILE))
    write_file($$QPB_VERSION_FILE, QPB_VERSION_H)
}
HEADERS += $$QPB_VERSION_FILE

# Run qmake again when VERSION changes (e.g. after replacing the folder).
QMAKE_INTERNAL_INCLUDED_FILES += $$QPB_ROOT/VERSION $$QPB_ROOT/cmake/qpbversion.h.in
